build:
	#g++ -Wall -Wno-unused-variable -Wno-unused-function main.cpp -o sec_camera -lpthread -I nps_utils
	g++ -Wall -Wno-unused-variable -Wno-unused-function jpg_send_test.cpp -o jpg_send_test -lpthread -I nps_utils
	#g++ -Wall message_buffer_test.cpp -o message_buffer_test -lpthread
	#g++  -Wall jpg_test.cpp -o jpg_test
	#g++  -Wall pipe_test.cpp -o pipe_test
	#g++  -Wall pipe_test2.cpp -o pipe_test2
