build:
	g++ -Wall -Wno-unused-variable -Wno-unused-function main.cpp -o sec_camera -lpthread -I nps_utils
	#g++ -Wall message_buffer_test.cpp -o message_buffer_test -lpthread
	#g++  -Wall jpg_test.cpp -o jpg_test
